name: metadata_god
description: Plugin for retrieving and writing audio tags/metadata from audio files
version: 0.3.0
homepage: https://github.com/KRTirtho/metadata_god

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.41.3
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.krtirtho.metadata_god
        pluginClass: MetadataGodPlugin
      linux:
        pluginClass: MetadataGodPlugin
      macos:
        pluginClass: MetadataGodPlugin
      ios:
        pluginClass: MetadataGodPlugin
      windows:
        pluginClass: MetadataGodPluginCApi
      web:
        fileName: metadata_god_web.dart
        pluginClass: MetadataGod
