[package]
name = "metadata_god"
version = "0.5.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
lofty = "0.21.1"
id3 = "1.14.0"
anyhow = "1.0.86"
