name: metadata_god
description: Plugin for retrieving and writing audio tags/metadata from audio files
version: 0.5.2+1
repository: https://github.com/KRTirtho/metadata_god/blob/main/packages/metadata_god
homepage: https://github.com/KRTirtho/metadata_god

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true