name: Build Dynamic Libraries
on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd rust && cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: rust/target/release/librust.so

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "adopt"
          java-version: "8"
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25b
          local-cache: true

      - run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
          cargo install cargo-ndk
          mkdir dist
          cd rust; cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 -t x86 -o ../dist build --release
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: |
            dist/armeabi-v7a/librust.so
            dist/arm64-v8a/librust.so
            dist/x86_64/librust.so
            dist/x86/librust.so
          if-no-files-found: error
      - if: ${{ failure() }}
        name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd rust && cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: |
            rust/target/release/rust.dll

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup target add aarch64-apple-ios aarch64-apple-darwin
          cd rust
          cargo build --release
          cargo build --release --target=aarch64-apple-darwin
          lipo -create -output librust.dylib target/release/librust.dylib target/aarch64-apple-darwin/release/librust.dylib
          cargo build --release --target=aarch64-apple-ios
      - uses: actions/upload-artifact@v3
        with:
          name: RustLib
          path: |
            rust/librust.dylib
            rust/target/aarch64-apple-ios/release/librust.a
